name: Backend Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: .
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKERHUB_IMAGE }}:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKERHUB_IMAGE }}

    - name: Pull the image to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PSW}}
        script: |
          docker image rm ${{ secrets.DOCKERHUB_IMAGE }} -f
          docker pull ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKERHUB_IMAGE }}:latest
          docker stop ${{ secrets.DOCKERHUB_IMAGE }}-c || true
          docker rm ${{ secrets.DOCKERHUB_IMAGE }}-c || true
          docker run -d -p 5002:5002 --restart on-failure:5 --name ${{ secrets.DOCKERHUB_IMAGE }}-c --network ${{vars.DOCKER_CONTAINER_NETWORK}} ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKERHUB_IMAGE }}:latest